version: "3.8"

services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: adv_book_db
    restart: unless-stopped
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=root"
      - "MONGO_INITDB_ROOT_PASSWORD=root"
    ports:
      - '27018:27017'